# Generated by Django 5.2.12 on 2026-03-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_remove_expense_google_table_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
    ]
